version: '{build}'
image: Visual Studio 2017
clone_depth: 1

branches:
  only:
  - master

configuration:
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - cmd: dotnet --version

build_script:
  - cmd: dotnet build ./src/OneDas.Hdf.Types/OneDas.Hdf.Types.csproj -c %CONFIGURATION% /p:Build=%APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet build ./samples/ExtensionSample/ExtensionSample.csproj -c %CONFIGURATION% /p:Build=%APPVEYOR_BUILD_NUMBER% /p:BuildProjectReferences=false

test_script:
  - cmd: dotnet test ./tests/OneDas.Core.Tests /p:Build=%APPVEYOR_BUILD_NUMBER% -c %CONFIGURATION%

artifacts:
  - path: ./artifacts/**/*.nupkg

deploy:
  provider: NuGet
  server: https://www.myget.org/F/onedas/api/v2/package
  api_key:
    secure: DVadlPknnKPMR4F2+3VqeU7BFFmtLcXDHzkySA590MqQNIdzbx8HRuaPwDVbHRqX
  skip_symbols: true
  artifact: /.*\.nupkg/ 