matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3

language: csharp
mono: none
dotnet: 2.1.105

branches:
  only:
  - master

before_script:
  - dotnet --version

script: 
  - dotnet build ./src/OneDas.Core/OneDas.Core.csproj -c %CONFIGURATION% /p:Build=%APPVEYOR_BUILD_NUMBER%
  - dotnet build ./src/OneDas.Hdf.Types/OneDas.Hdf.Types.csproj -c %CONFIGURATION% /p:Build=%APPVEYOR_BUILD_NUMBER%
  - dotnet build ./samples/DataGatewaySample/DataGatewaySample.csproj -c %CONFIGURATION% /p:Build=%APPVEYOR_BUILD_NUMBER%
  - dotnet test ./tests/OneDas.Core.Tests -c %CONFIGURATION% /p:Build=%APPVEYOR_BUILD_NUMBER% /p:BuildProjectReferences=false