matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3

language: csharp
mono: none
dotnet: 2.1.105

branches:
  only:
  - master

before_script:
  - dotnet --version

script: 
  - dotnet build ./src/OneDas.Hdf.Types/OneDas.Hdf.Types.csproj
  - dotnet build ./samples/ExtensionSample/ExtensionSample.csproj /p:BuildProjectReferences=false
  - dotnet test ./tests/OneDas.Core.Tests -c %CONFIGURATION%